[package]
name = "scholar_scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
reqwest = "0.12.12"
scraper = "0.22.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
tokio = { version = "1.43.0", features = ["full"] }
